### PR TITLE
force ssh:// on clone

### PR DESCRIPTION
**Pull request by mfsysprog**
---------------------
Cloning a repo is only supported using ssh. The panel would accept https
and this leads to corruption of the repository. The only way to check if
ssh is used, is to force the url to start with ssh://

### CODE REVIEW

**Comment by lbdyck** [comment]
While I agree with this issue to a point the solution is not what I would agree to - the reason is that currently the user can copy the clone command from github, bitbucket, gitlab, etc. and then just paste it into the clone field on the zigicc panel. With this change the user must paste and then edit before using it. I'd like to see a different implementation (not sure what at this point)

my $0.02 on the topic.

**Comment by mfsysprog** [comment]
Hello Lionel, 
My first fix attempt was to check for a @ in the url. And event though this is normally the case when cloning from github (the git@ part), it is possible that some other sites might not require the addition of a user. 
Perhaps an option would be to use my fix, but fill in the ssh:// on the panel by default?

**Comment by lbdyck** [comment]
I checked github, bitbucket, and gitlab and for https clones all the commands start with https:// so checking for that would be my suggestion instead of forcing ssh:// or checking for ssh://.  Check for what we don't want should be fine.  Unless I'm missing something (which is possible this morning).

**Comment by mfsysprog** [comment]
I started down that path, but at some point reading the different protocol options I decided that it would be better to test for the 'positive' case, since all the supported protocol (ssh, https, local and git) allow for specifying a string without the protocol if I'm correct (in which case it is hard to decide if the user is indeed using the correct method, or is just leaving of the http part for example). 
Also, it makes it more clear that zigi only supports ssh (for now).

**Comment by mfsysprog** [comment]
I will create a new pull request that will prefill the remote on the panel with ssh:// and position the cursor directly after that. You can then decide if that works ok for you, if not I will go the other suggested route of doing 'negative testing'

**Comment by lbdyck** [comment]
Take a look at what each git server (i.e. github) provides in the clipboard for the clone - doing a pre-fill may present a problem for what gets pasted.  And the user can still just paste over what you pre-fill.  The negative testing seems the best (imho).  @Henri may have other thoughts.

**Pull request closed without merging**
