### PR TITLE
Add incldiff flag to gitlog

### PR DESCRIPTION
**Pull request by leeb-dev**
I prefer the default 'git log' output, so this adds a field in the gitlog popup to allow log display excluding diffs. 

Open to any suggestions and criticism - it's my first attempt at ISPF development!

### CODE REVIEW

**Comment by lbdyck** [comment]
I like it and your 1st attempt is appreciated.

**Comment by lbdyck** [comment]
I couldn't figure out how to pull your updates into my fork so I made them manually.

Take a look at https://github.com/lbdyck/zigi for branch v2r0-dev which has your update and a LOT more. Would appreciate other eyes checking it and breaking it before Henri takes it :)

My e-mail is lbdyck@gmail.com

**Comment by leeb-dev** [comment]
I'll take a look at v2r0-dev - thanks!

You (should) have email.

**Comment by wizardofzos** [comment]
I’ll merge it into the “rc” branch over the weekend too. Awesome addition

**Comment by leeb-dev** [comment]
Thanks! Starting small :)
Was thinking maybe I'd look at adding some more of the output options (pretty printing etc)?

**Comment by leeb-dev** [comment]
Oh, while I remember - do I need to be doing anything with the ID of PDS members in any future PRs?

**Comment by lbdyck** [comment]
As you can see the userids are consistent. ZIGI## where ## is the version release. If you use the SET command on the repo dataset panel you can force it to reset the IDs before the commit.

**Comment by lbdyck** [comment]
You can pull in my v2r0-dev fork and merge it into the rc if you like.

Lionel B. Dyck <sdg>  sent from my iPad
Senior Software Engineer
21st Century Software
940 West Valley Road<x-apple-data-detectors://1>
Suite 1604<x-apple-data-detectors://1>
Wayne, PA 19087<x-apple-data-detectors://1>
www.21stcenturysoftware.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.21stcenturysoftware.com&d=DwMFAw&c=jf_iaSHvJObTbx-siA1ZOg&r=O9Yt-0q7UsiUaBSmIwennw&m=ze6XIIO6XqAm_rFtn1zF8hbYK-3sN7_ZCV0uDjSUFWI&s=C0xITJTTxnixxEtO9UXS82AE82iV9VszD9838jfcEcs&e=>

lioneld@21csw.com<mailto:lioneld@21csw.com>
(800) 555-6845  x610<tel:(800)%20555-6845;610>
(610) 710-4832<tel:(610)%20710-4832> – Office

From the Leaders in Data Stewardship™

THIS E-MAIL MAY CONTAIN PRIVILEGED, CONFIDENTIAL, COPYRIGHTED, OR OTHER LEGALLY PROTECTED INFORMATION. IF YOU ARE NOT THE INTENDED RECIPIENT (EVEN IF THE E-MAIL ADDRESS ABOVE IS YOURS), YOU MAY NOT USE, COPY, OR RE-TRANSMIT IT. IF YOU HAVE RECEIVED THIS BY MISTAKE PLEASE NOTIFY US BY RETURN E-MAIL, THEN DELETE. THANK YOU

On Dec 14, 2019, at 9:56 AM, wizardofzos <notifications@github.com> wrote:

﻿I’ll merge it into the “rc” branch over the weekend too. Awesome addition

**Comment by wizardofzos** [comment]
I'll merge this into a v1r4-rc :)

**Pull request merged**
